version: '3.8'

services:
  todo:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
      - ~/.ivy2:/root/.ivy2  # Keep downloaded dependencies locally
      - ~/.sbt:/root/.sbt
    entrypoint: sbt
    command: run

  postgres:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  pgdata:
